def read_inputs(filename : str) -> array[]:
    """
    Go row by row in inputted txt file via for loop
    could create a list type of thing =, must identify first character, only based on the numbers of regs 
    in instructs do I know if there is a stall in decode
    #check first letter:
    #R: no stall
    #I: no stall
    #L: stall!
    #S: no stall
    what insturcts required and the order of it
    """
    instructions = []
    with open(filename, 'r') as file:
        for line in file:
            for char in line:
                if char.equals('R'):

                elif char.equals('I'):

                elif char.equals('L'):

                elif char.equals('S'):

            instructions.append(line)
    return instructions
    
def fetch(instruction : str, indices : str, cycle : int, stall : bool) -> None:
    """
    similar to decode, instruction, cycle, stall are parameter. Stall is generated by decode.
    Any pipleline produce stall at decode, also effects fetch (stall =0/1) goes to fetch
    can move the fetched instruction to decode if decode is not
    stalled; incoming instruction comes from next unfetched location
    """

    

#if stall is true it does a pass statement and skips a stall cycle
#bc each next cycle depends on previous # cycle, they can all update seemlessly
#indices is keeping track of cycle count?? list is the pipeline
#indicies: F,D,E,W, etc

def decode(instruction : str, indices : str, cycle : int) -> None:
    """
    func inputs, given in function inputs 
    and cycle count (what row im on) instruction is you know what instruct it is, mention values to go from register memory values
    should know prev 2 instructs aswell, if inputs for loads match maybe need a stall
    checks for hazards. If there are no hazards, then the instruction
    can advance
    """
    pass

def execute(instruction : str, indices : str, cycle : int) -> None:
    """
    straightfoward, input intsruct, indices, cycle: here we are checking 

     would perform the operation, but we are not emulating instruction
    execution, just scheduling
    """
    pass

def memory(instruction : str, indices : str, cycle : int) -> None:
    """
    keeps track of previous!, must capture a stall when it happens -> update the cycle
    how does memory know what cycle execute finished in? -> I HAVE NO CLUE

    would perform any memory lookup, but we are not emulating
    instruction execution, just scheduling. Results from R and I types would be
    available here for forwarding

    """
    pass

def writeback(instruction : str, indices : str, cycle : int, nextLineThing(completed_insts_maybe) : bool) -> None:
    """
    where we write to output file?? Instruct, indices, cycle, another flag to show
    pipeline is completed, go onto the next row (call whatever I want).
    Hint: completedInsts. i count is the length pf my instruction set/number of rows (make sure icount is more than my completed num of rows)

    would update register contents, but we are not emulating
    instruction execution, just scheduling. Results from L types would be
    available here for forwarding; instructions leave pipeline on completing
    writeback
    """
    pass

def init_structures_and_counts(instructions) -> None:
    """
    I think this is where i would want to use the idea of latches (E/M registers that store the instruct that last finished the stage)
    """
    state = []
    for i, instr in enumerate(instructions):
        state.append({
            "index" = i,
            "stage" = None,
            "cycle_entered" = None,
            "stall" = False,
        })

def emit_output() -> None:
    """
    I think this is where I'm supposed to spit stuff into output.txt
    maybe I need to collect stuff from the stage functions here??????
    """
    pass


def main(argc : int, argv : str) -> int: # how does char** translate to python? double pointer, right?
    """
    argc = cycle counts
    argv = current instruction
    """
    init_structures_and_counts(argc,argv) # WHAT DOES THIS DO
    ... 
    while(completed_insts < icount):
        writeback()
        memory(...)
        execute(...)
        decode(...)
        fetch(<L,4,6,5>, E, 0) #?????
        cyclecount += cyclecount
  
    emit_output()
    return 0


# 